[project]
name = "la-fires2"
version = "0.1.0"
description = "Create input files for BEPS for la_fire experiment"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "tqdm>=4.67.1",
]
